// Builds src/lib/library-data.js from library/roots.pem (Mozilla roots) and library/intermediates/*.pem.
// Keeps only intermediates that are CA certificates, currently valid, and whose signature verifies
// against a Mozilla root or another kept intermediate.
import fs from 'node:fs';
import path from 'node:path';
import forge from 'node-forge';
import { parseCert } from '../src/lib/cert.js';
import { verifySignature } from '../src/lib/verify.js';
import { spkiDer } from '../src/lib/cert.js';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const pemBlocks = (t) => [...t.matchAll(/-----BEGIN CERTIFICATE-----([\s\S]*?)-----END CERTIFICATE-----/g)].map((m) => forge.util.decode64(m[1].replace(/\s+/g, '')));

const roots = pemBlocks(fs.readFileSync(path.join(root, 'library/roots.pem'), 'utf8')).map((d) => parseCert(d, 'root')).filter(Boolean);
const dir = path.join(root, 'library/intermediates');
let inter = [];
for (const f of fs.readdirSync(dir).sort()) for (const d of pemBlocks(fs.readFileSync(path.join(dir, f), 'utf8'))) { const c = parseCert(d, f); if (c) inter.push(c); }

const now = Date.now();
const seen = new Set();
inter = inter.filter((c) => {
  if (seen.has(c.sha256)) return false; seen.add(c.sha256);
  if (!c.isCA) { console.warn('skip (not a CA):', c.subject.short); return false; }
  if (c.selfSigned) { console.warn('skip (self-signed):', c.subject.short); return false; }
  if (c.notAfter < now || c.notBefore > now) { console.warn('skip (not currently valid):', c.subject.short); return false; }
  return true;
});

// keep intermediates that chain to a root (iteratively, to allow cross-signed / two-level chains)
const kept = new Set();
let changed = true;
while (changed) {
  changed = false;
  for (const c of inter) {
    if (kept.has(c)) continue;
    const issuers = [...roots.filter((r) => r.subjectDer === c.issuerDer), ...inter.filter((i) => kept.has(i) && i.subjectDer === c.issuerDer)];
    for (const iss of issuers) if (await verifySignature(c, iss.pub)) { kept.add(c); changed = true; break; }
  }
}
for (const c of inter) if (!kept.has(c)) console.warn('skip (does not chain to a Mozilla root):', c.subject.short);

const b64 = (s) => forge.util.encode64(s);
const out = {
  date: new Date().toISOString().slice(0, 10),
  intermediates: [...kept].sort((a, b) => a.subject.short.localeCompare(b.subject.short)).map((c) => b64(c.der)),
  roots: roots.map((r) => ({ name: r.subject.short, subject: b64(r.subjectDer), spki: b64(spkiDer(r.pub) || '') })).filter((r) => r.spki),
};
fs.writeFileSync(path.join(root, 'src/lib/library-data.js'),
  `// Generated by scripts/build-library.mjs on ${out.date}. Do not edit by hand.\nexport default ${JSON.stringify(out)};\n`);
console.log(`library: ${out.intermediates.length} intermediates, ${out.roots.length} roots`);
for (const c of [...kept]) console.log('  +', c.subject.short, '— until', c.notAfter.toISOString().slice(0, 10));
